export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const GET_TODO_LIST = 'GET_TODO_LIST';
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
export const REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM';
export const SEARCH_TODO_ITEMS = 'SEARCH_TODO_ITEMS';